DROP TABLE IF EXISTS week_results;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS week_locks;

DROP TABLE IF EXISTS lineups;

DROP TABLE IF EXISTS players;

DROP TABLE IF EXISTS league_bookmarks;

